<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <title>Products sorting</title>

</head>
<body>
    

<form action="RequestModel.php" method="GET">
     <lable for="id_brand_input">Enter id of brand</lable>
     <input type="text" id="id_brand" name="id_brand" value="all">
     </br></br>
     <label for="id_availability">Choose a availability of product:</label>
     <select name="id_availability" id="field_id_availability">  
         <option value="all">Select: all </option>
         <option value="1">Is available: 1 </option>
         <option value="2">To specify the delivery: 2 </option>
         <option value="3">Under the order: 3 </option>
     </select>
     </br></br>
     <label for="price">Price from(between 1 and 10000000000):</label>
     <input type="range" id="item_price_from" name="from_price" value="1" min="1" max="10000000000">
     </br></br>
     <label for="price">Price to(between 1 and 10000000000):</label>
     <input type="range" id="item_price_to" name="to_price" min="1" max="10000000000">
     </br></br>
     <label for="price_sorting_order">Choose a order of sorting:</label>
     <select name="id_sortingBy" id="sortBy">
         <option value="price_in_uah">Use price for sorting </option>
         <option value="current_price.name">Use name for sorting </option>
     </select>
     </br></br>
     <label for="is_desc">Choose descending or ascending sorting order:</label>
     <select name="id_isDesc" id="isDesc">
         <option value="ASC">Use ascending order for sorting </option>
         <option value="DESC">Use descending order for sorting </option>
     </select>
     </br></br>
     <button type="button"  onclick="send_request()" name="request_button">Send request</button>
</form>

<div id="product_list">List of products</div>


<script>

function get_url() {
    var url = window.location.pathname.split("/");
    var id_category = url[3];
    return id_category
}



function send_request(id_brand) {
    // code below grabs value from input element with correct id of item 
      id_category = get_url();  

      var id_brand = $("#id_brand").val();
      var id_availability = $("#field_id_availability").val();
      var item_price_from = $("#item_price_from").val();
      var item_price_to = $("#item_price_to").val();
      var sort_by = $("#sortBy").val();
      var is_desc = $("#isDesc").val();
      
    
    $.ajax({                            
        dataType: "JSON",
        method: "GET",
        url: "http://example.com/request/grab_product/?id_category=" + id_category,
        data: {
            id_brand: id_brand,
            id_availability: id_availability,
            price: {
                item_price_from: item_price_from,
                item_price_to: item_price_to,
            },
            sorting: {
                sort_by: sort_by, // price or name
                is_desc: is_desc, // true or false
            }
         },
        success: function(response) {
            if (response.success == false ) {
                alert(response.posted);
            } else {
                alert("Success case");


                $.each(response.array, function(i, product) {
                 content = '<p>' + "Name of product: " + product.name + '</p>';
                 content += '<p>' + "Product id_availability: " + product.id_availability + '</p>';
                 content += '<p>' + "Product price in UAH: " + product.price_in_uah + '</p>';
                 
                 $(content).appendTo("#product_list");
                });

                total_quantity = '<h3>' + "Total quantity: " + response.total_quantity[0].totalQuantityOfGoods + '</h3>';
                $(total_quantity).appendTo("#product_list");
                                      
                total_filtered_quantity = '<h3>' + "Total filtered quantity: " + response.total_filtered_quantity[0].totalNumberOfFilteredItems + '</h3>';
                $(total_filtered_quantity).appendTo("#product_list");                                                                              
                
                   }

        },
        error: function(response) {
          alert(response.success);
          alert("Error in send_request function");
        }
    });
    
}
</script>

</body>
</html>
